# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3b04dfe67535ffb19e5b6af3f000bcc6be5d425ae8fea249d4dee20d7009fdcf9453d3da2415b035d581a68806e15539ffd6b0eb1ce7ff98d84f7b992df37839

test:
  secret_key_base: 7ec79e59ed41c8b4bb8cb6ffd00a267c16345e5b995414636f618ae8239ad6d6d3a5fff874b5991a47e507d58060af442f0219f9bb14439db4c4eec5f4a64816

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
